# Generated by Django 3.1.5 on 2021-01-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_auto_20210122_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='drone_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xx', to='drones.dronecategory'),
        ),
    ]
