# Generated by Django 3.1.5 on 2021-01-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_auto_20210123_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drone',
            options={'ordering': ('nameaz',)},
        ),
        migrations.RenameField(
            model_name='drone',
            old_name='name',
            new_name='nameaz',
        ),
    ]
