# Generated by Django 3.1.5 on 2021-01-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0005_auto_20210123_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drone',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='dronecategory',
            options={'ordering': ('namenew',)},
        ),
        migrations.RenameField(
            model_name='drone',
            old_name='nameaz',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dronecategory',
            old_name='name',
            new_name='namenew',
        ),
    ]
