# Generated by Django 3.1.5 on 2021-01-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0006_auto_20210123_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='drone_category',
            new_name='drone_categoryss',
        ),
    ]
