# Generated by Django 3.1.5 on 2021-01-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0012_auto_20210123_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='drone_categoryss',
            new_name='drone_category',
        ),
    ]
