# Generated by Django 3.1.5 on 2021-01-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0015_auto_20210123_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='xsxsxs',
            new_name='aqaq',
        ),
    ]
