# Generated by Django 3.1.5 on 2021-01-23 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0017_auto_20210123_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='aqaq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thenDro', to='drones.dronecategory'),
        ),
    ]
